server:
  port: 9999
spring:
  datasource:
    username: root
    password: 1234567
    url: jdbc:mysql:///managesystem
  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    com.ysevenk: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.ysevenk.*.entity